.github/CODEOWNERS, controller/client/controller_client.go, controller/client/delegating_client.go, controller/client/delegating_handler_client.go, controller/client/delegating_handler_client_test.go, controller/client/monitor_client.go, controller/client/suite_test.go, go.mod, go.sum, monitor/context/README.md, monitor/context/context.go, monitor/context/context_test.go, monitor/metrics/vars.go, multicluster/client_test.go, util/k8s/object.go, util/k8s/object_test.go, util/rand/strings.go, util/rand/strings_test.go, util/runtime/caller.go, util/test/tester/client.go
=> Feat: add client package

go.mod, go.sum, util/k8s/object.go, util/k8s/object_test.go, util/k8s/patch/patch.go, util/k8s/patch/patch_test.go, util/test/object/unknown.go
=> Feat: add three way merge patch

util/sync/map.go, util/sync/map_test.go
=> Feat: add support for sync map

util/slices/parallel.go, util/slices/parallel_test.go, util/slices/utils.go, util/slices/utils_test.go
1. support `slices.Filter`, `slices.Index`, `slices.Find`, `slices.Flatten`
2. supprot `slices.ParFor`, `slices.ParMap` (Parallel Execution) for array items.
=> Feat: add support for par slices

util/k8s/namespace.go, util/test/tester/client.go
=> Feat: add func for clear ns

util/k8s/object.go, util/k8s/object_test.go, util/maps/sync.go, util/maps/sync_test.go, util/maps/utils.go, util/maps/utils_test.go
Add 
1. AsStructured: convert unstructured to typed object
2. SyncMap Load: support load whole map into SyncMap
3. Map & Copy: support map & copy for map object
=> Feat: add util functions

.github/workflows/unit-test.yml
=> Chore: upgrade codecov ci

util/log/flag.go
=> Feat: optimize log flag

cue/cuex/compiler.go, cue/cuex/compiler_test.go
=> Feat: support raw extension for extra data in cuex

cue/cuex/compiler.go, cue/cuex/compiler_test.go, cue/cuex/providers/kube/kube.cue, cue/cuex/providers/kube/kube.go, cue/cuex/providers/kube/kube_test.go
=> Feat: add kube.apply and fix cuex.withExtraData

cue/cuex/providers/http/http.go
Signed-off-by: iyear <ljyngup@gmail.com>
I am trying to write a DEMO for automatic generation of CUE scheme from Go struct. And I found some problems here.
In addition to the PR fix, the types of `request.header` and `request.trailer([string]: string)` in `CUE` do not correspond to `http.Header(map[string][]string)`. But this involves a lot of documentation changes, and I'm not sure if I should change it.
=> Fix: inconsistent RequestVars fields

cue/cuex/providers/http/http.cue
=> Fix: http provider use incorrect template after add

apis/cue/v1alpha1/package_types.go, cue/cuex/compiler.go, cue/cuex/runtime/package.go, cue/cuex/runtime/provider.go, cue/cuex/runtime/provider_test.go, cue/cuex/suite_test.go, cue/server/server.go, cue/util/printer.go, cue/util/printer_test.go, util/test/bootstrap/kubebuilder.go
1. External provider use `$params` as input and `$returns` as output.
2. Support https protocol for external provider. By default, it will use insecure-skip-verify.
3. Split cue printer into separate functions.
4. Update CI bootstrap to allow absolute crd path.
5. External provider will inject "#do" value to http request header "CueX-External-Provider-Function".
=> Feat: support cue printer & add support for protocol https

cue/cuex/compiler.go, cue/cuex/compiler_test.go, util/runtime/nil.go, util/runtime/nil_test.go
=> Fix: nil check panic

cue/util/iterate.go, util/maps/utils.go, util/maps/utils_test.go
1. split FieldValues for outer use.
2. add maps.From
=> Feat: split FieldValues function for cue

go.mod, go.sum, util/hash/hash.go, util/hash/hash_test.go, util/jsonutil/convert.go, util/jsonutil/convert_test.go, util/jsonutil/fieldpath.go, util/jsonutil/fieldpath_test.go, util/k8s/apply/client.go, util/k8s/apply/client_test.go, util/k8s/object.go, util/k8s/patch/patch.go, util/k8s/patch/patch_test.go
1. Add hash.
2. Add CopyInto & FieldPath for jsonutil.
3. Migrate apply client from kubevela main repo.
4. Update patch pkg for main repo use.
=> Feat: add utility

multicluster/client.go
gatedClient has been fully replaced by remoteClusterClient
=> Remove gatedClient

go.mod, go.sum, util/compression/types.go
fix the concurrent number of zstd encoders in k8s container and support zstd configuration re-initialization
=> Fix: Vela uses zstd compression function causing OOM (#92)

.github/workflows/unit-test.yml
Builds are failing due to deprecated Github cache action. [Example](https://github.com/kubevela/pkg/actions/runs/13830772326)
Bump version to v4
N/A
Matching [kubevela version](https://github.com/kubevela/kubevela/blob/master/.github/workflows/unit-test.yml#L55).
=> Chore: Update Github Actions cache from deprecated v2 to v4

cue/cuex/externalserver/server.go, cue/cuex/externalserver/server_test.go, cue/cuex/runtime/provider.go, cue/cuex/runtime/tracer.go, cue/cuex/runtime/tracer_test.go, go.mod
Adds tracing and baggage (app context) support using OTel for outbound CueX requests. 
The externalserver package has been updated to reconstruct the context from the received headers. 
I have:
PR includes unit tests for both the outbound and inbound functionality. 
Manual testing has been conducted to ship application workflow context & trace IDs from a Kubevela Application to a CueX server. 
N/A
=> Feat: Add OTel Tracing Headers and Baggage with CueX Requests
